services:
  - type: web
    name: skillswap-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
